module.exports = {
    itemNames: {
        r: 'Radical',
        k: 'Kanji',
        v: 'Vocab',
    },
    wkItemNames: {
        r: 'radical',
        k: 'kanji',
        v: 'vocabulary',
    },
    wkItemColors: {
        r: 0x55abf2,
        k: 0xf032b1,
        v: 0xbb31de,
    },
    mnemonicNames: {
        m: 'meaning',
        r: 'reading',
        b: 'reading and meaning',
    },
    emotes: {
        "A": "🇦",
        "B": "🇧",
        "C": "🇨",
        "D": "🇩",
        "E": "🇪",
        "F": "🇫",
        "G": "🇬",
        "H": "🇭",
        "I": "🇮",
        "J": "🇯",
        "K": "🇰",
        "L": "🇱",
        "M": "🇲",
        "N": "🇳",
        "O": "🇴",
        "P": "🇵",
        "Q": "🇶",
        "R": "🇷",
        "S": "🇸",
        "T": "🇹",
        "U": "🇺",
        "V": "🇻",
        "W": "🇼",
        "X": "🇽",
        "Y": "🇾",
        "Z": "🇿",
        'BB': '🅱️',
        'wave': '👋',
    }
}